### ISSUE TITLE
CompanyToIT: Modelgen does not work correctly

### ISSUE THREAD

**Issue by NilsWeidmann** [eMoflon/emoflon-ibex-tests#26]
Correspondence model can contain several admins, while source and target model do not have one.
Admin generation only works when attribute condition is switched off.

**Comment by anthonyanjorin** [comment]
Can we close this now?  Wasn't this due to a faulty dev workspace?

**Comment by anthonyanjorin** [comment]
@NilsWeidmann Is this working now?
