### ISSUE TITLE
Now that we have integrated eMoflon core again, we should remove generated files

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-ibex-tests#30]
We should convert all metamodel projects to eMoflon projects, enable code generation for them, and get rid of all generated code and .genmodels.

**Comment by patrickrobrecht** [comment]
After the meta-model projects are migrated to eMoflon EMF Projects, the `.gitignore` should be updated to ignore `/gen/` and `/model/*.genmodel` (cp. FerrymanProblem project as an  example).
