### ISSUE TITLE
Performance of the TGG FamilyWithSiblingsToPersons_MA is quite bad

### ISSUE THREAD

**Issue by NilsWeidmann** [eMoflon/emoflon-ibex-tests#55]
The MODELGEN operationalization does not terminate within 2 minutes for 500 elements

**Comment by anthonyanjorin** [comment]
Based on our performance comparison, FamilyToPersons_MA is also very inefficient, and I don't see the reason why.  I suggest we profile at least these two TGGs to detect any hotspots (related to MA) we can fix.
